# Generated by Django 4.1.7 on 2023-03-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(choices=[('healthy', 'HEALTHY'), ('programming', 'PROGRAMMING'), ('productive', 'PRODUCTIVE'), ('desigin', 'DESIGIN'), ('self_improvement', 'Self_Improvement')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique_for_date=True)),
                ('image', models.ImageField(upload_to='image')),
                ('content', models.TextField()),
                ('extra_like', models.IntegerField(default=0)),
                ('dis_extra_like', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category')),
            ],
        ),
    ]
