# Generated by Django 4.1.7 on 2023-03-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_article',
            field=models.BooleanField(default=True),
        ),
    ]
