# Generated by Django 4.1.7 on 2023-03-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_main_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_article',
            field=models.BooleanField(),
        ),
    ]
