# Generated by Django 4.1.7 on 2023-03-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_main_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gmail', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.CharField(choices=[('healthy', 'HEALTHY'), ('image', 'photo'), ('programming', 'PROGRAMMING'), ('productive', 'PRODUCTIVE'), ('desigin', 'DESIGIN'), ('self_improvement', 'Self_Improvement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='post.category'),
        ),
    ]
