# Generated by Django 4.1.7 on 2023-04-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_contact_alter_category_content_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='read_count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='read_count', to='post.postcount'),
            preserve_default=False,
        ),
    ]
